owner: Diff-Network
repo: network-status

sites:
  - name: Web Interface
    url: https://diff.network/about
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000
    
  - name: API Service
    url: https://diff.network/api/v1/instance
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    
  - name: Streaming API
    url: https://diff.network/api/v1/streaming/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000
    
  - name: Media Storage
    url: https://entity.diff.network/status_check.png
    expectedStatusCodes:
      - 200
      - 304
    maxResponseTime: 2000

  - name: Ping CDN (Cloudflare)
    url: diff.network
    type: globalping
    location: Singapore

  - name: Ping Server (Singapore, sgp-01)
    url: $ENDPOINT_MASTODON_SERVER
    type: globalping
    check: tcp-ping
    location: Singapore
    ipv6: false

status-website:
  cname: status.diff.network
  name: Diff.Network Status
  introTitle: "**Diff.Network** provides real-time status here."
  introMessage: Check uptime and availability of our instance and infrastructure.
  
  navbar:
    - title: Home
      href: https://diff.network
    - title: About
      href: https://diff.network/about
    - title: GitHub
      href: https://github.com/Diff-Network/
  
  logoUrl: https://entity.diff.network/status_check.png
  theme: light
  graphs: true
  publishDrafts: false
  footerText: ""

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
